<<<<<<< HEAD
[secrets]
=======
[secrets]
>>>>>>> db9a8837472f78368cb2f23749bbbeaeca1e028b
DATABASE_URL = "postgresql://postgres.ddduccrecwuedpdprnah:pK4ViLhZhplWcjdp@aws-0-sa-east-1.pooler.supabase.com:6543/postgres"